
package frame.admin;

import frame.mahasiswa.KrsMhsFrame;
import java.awt.Color;
import util.FrameSetting;

/**
 *
 * @author Randa
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        FrameSetting.setFrame(this);
        jPanel2.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bKelas = new javax.swing.JLabel();
        bJadwal = new javax.swing.JLabel();
        bKrs = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        bExit = new javax.swing.JLabel();
        bMakul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bDosen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bMhs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(51, 153, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATA KRS");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 440, 250, 210));

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA JADWAL");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 250, 210));

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DATA KELAS");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 250, 210));

        jPanel6.setBackground(new java.awt.Color(204, 153, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA MAHASISWA");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 250, 210));

        jPanel5.setBackground(new java.awt.Color(102, 153, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA DOSEN");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 250, 210));

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" DATA MATA KULIAH");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 250, 210));

        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/btn_kelas.png"))); // NOI18N
        bKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKelasMouseClicked(evt);
            }
        });
        jPanel2.add(bKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 450, 240, 200));

        bJadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/btn_jadwal.png"))); // NOI18N
        bJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bJadwalMouseClicked(evt);
            }
        });
        jPanel2.add(bJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 446, 250, 200));

        bKrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/btn_krs.png"))); // NOI18N
        bKrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bKrsMouseClicked(evt);
            }
        });
        jPanel2.add(bKrs, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 240, 190));

        jLabel9.setBackground(new java.awt.Color(27, 178, 115));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(246, 248, 246));
        jLabel9.setText("Admin");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 66, 370, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/user.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 90));

        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/logout.png"))); // NOI18N
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });
        jPanel2.add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 70, 90));

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/exit.png"))); // NOI18N
        bExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExitMouseClicked(evt);
            }
        });
        jPanel2.add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 90, 90));

        bMakul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/btn_makul.png"))); // NOI18N
        bMakul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMakulMouseClicked(evt);
            }
        });
        jPanel2.add(bMakul, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 240, 200));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 474, 280, 140));

        bDosen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bDosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/btn_dosen.png"))); // NOI18N
        bDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bDosenMouseClicked(evt);
            }
        });
        jPanel2.add(bDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 216, 250, 200));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MENU ADMIN");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 140));

        bMhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/btn_mhs.png"))); // NOI18N
        bMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bMhsMouseClicked(evt);
            }
        });
        jPanel1.add(bMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 250, 210));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 860));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitMouseClicked

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        // TODO add your handling code here:
        new frame.login.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLogoutMouseClicked

    private void bMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMhsMouseClicked
        // TODO add your handling code here:
        new MahasiswaFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMhsMouseClicked

    private void bDosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bDosenMouseClicked
        // TODO add your handling code here:
        new DosenFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bDosenMouseClicked

    private void bMakulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMakulMouseClicked
        // TODO add your handling code here:
        new MakulFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bMakulMouseClicked

    private void bKelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKelasMouseClicked
        // TODO add your handling code here:
        new KelasFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bKelasMouseClicked

    private void bJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bJadwalMouseClicked
        // TODO add your handling code here:
        new JadwalFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bJadwalMouseClicked

    private void bKrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bKrsMouseClicked
        // TODO add your handling code here:
        new KrsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bKrsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bDosen;
    private javax.swing.JLabel bExit;
    private javax.swing.JLabel bJadwal;
    private javax.swing.JLabel bKelas;
    private javax.swing.JLabel bKrs;
    private javax.swing.JLabel bLogout;
    private javax.swing.JLabel bMakul;
    private javax.swing.JLabel bMhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
