
package frame.mahasiswa;

import frame.admin.*;
import java.awt.Color;
import model.Mhs;
import util.FrameSetting;

/**
 *
 * @author Randa
 */
public class MenuUtamaMhs extends javax.swing.JFrame {
    private Mhs mhs;
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtamaMhs() {
        initComponents();
        FrameSetting.setFrame(this);
        jPanel2.setBackground(new Color(0,0,0,0));
    }
    
    /**
     * Method Constructor
     * @param mhs 
     */
    public MenuUtamaMhs(Mhs mhs) {
        initComponents();
        this.mhs = mhs;
        FrameSetting.setFrame(this);
        jPanel2.setBackground(new Color(0,0,0,0));
        lUser.setText(mhs.getNama());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnJadwalMHS = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDosenMHS = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnKRSMHS = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bLogout = new javax.swing.JLabel();
        bExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJadwalMHS.setBackground(new java.awt.Color(153, 204, 255));
        btnJadwalMHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJadwalMHSMouseClicked(evt);
            }
        });
        btnJadwalMHS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DATA JADWAL");
        btnJadwalMHS.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel2.add(btnJadwalMHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 250, 210));

        btnDosenMHS.setBackground(new java.awt.Color(102, 153, 0));
        btnDosenMHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDosenMHSMouseClicked(evt);
            }
        });
        btnDosenMHS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DATA DOSEN");
        btnDosenMHS.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jPanel2.add(btnDosenMHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 250, 210));

        btnKRSMHS.setBackground(new java.awt.Color(51, 153, 255));
        btnKRSMHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKRSMHSMouseClicked(evt);
            }
        });
        btnKRSMHS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATA KRS");
        btnKRSMHS.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jPanel2.add(btnKRSMHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 250, 210));

        lUser.setBackground(new java.awt.Color(27, 178, 115));
        lUser.setFont(new java.awt.Font("Berlin Sans FB", 0, 22)); // NOI18N
        lUser.setForeground(new java.awt.Color(246, 248, 246));
        lUser.setText("User");
        jPanel2.add(lUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 66, 370, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/user.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 70, 90));

        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/logout.png"))); // NOI18N
        bLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLogoutMouseClicked(evt);
            }
        });
        jPanel2.add(bLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 70, 90));

        bExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/button/exit.png"))); // NOI18N
        bExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bExitMouseClicked(evt);
            }
        });
        jPanel2.add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 90, 90));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 474, 280, 140));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MENU MAHASISWA");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 140));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 790));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 860));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1080, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bExitMouseClicked

    private void bLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLogoutMouseClicked
        // TODO add your handling code here:
        new frame.login.Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bLogoutMouseClicked

    private void btnKRSMHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKRSMHSMouseClicked
        // TODO add your handling code here:
          new KrsMhsFrame(mhs).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKRSMHSMouseClicked

    private void btnDosenMHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDosenMHSMouseClicked
        // TODO add your handling code here:
         new DosenMhsFrame(mhs).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDosenMHSMouseClicked

    private void btnJadwalMHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJadwalMHSMouseClicked
        // TODO add your handling code here:
          new JadwalMhsFrame(mhs).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJadwalMHSMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaMhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaMhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bExit;
    private javax.swing.JLabel bLogout;
    private javax.swing.JPanel btnDosenMHS;
    private javax.swing.JPanel btnJadwalMHS;
    private javax.swing.JPanel btnKRSMHS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lUser;
    // End of variables declaration//GEN-END:variables
}
